/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmployeeAccount: typeof import('./src/components/EmployeeAccount.vue')['default']
    ExecutiveDiscipline: typeof import('./src/components/ExecutiveDiscipline.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Tasks: typeof import('./src/components/Tasks.vue')['default']
  }
}
